allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - eslint@10.6.0
peerDependencyRules:
  allowedVersions:
    eslint-plugin-import>eslint: ^10.0.0
    eslint-plugin-jsx-a11y>eslint: ^10.0.0
    eslint-plugin-react>eslint: ^10.0.0
